parameters:

    scribe.cache.userland.class:      Scribe\CacheBundle\Component\Caching\UserlandApcuCache
    scribe.cache.userland.twig.class: Scribe\CacheBundle\Templating\Extension\UserlandCacheExtension

services:

    scribe.cache.userland:
        class:     %scribe.cache.userland.class%
        tags:
            - { name: caching }

    scribe.cache.userland.twig:
        class:     "%scribe.cache.userland.twig.class%"
        arguments: [ "@scribe.cache.userland" ]
        tags:
            - { name: twig.extension, alias: cache.twig }