checks:
    php: true
tools:
    external_code_coverage: true
filter:
    excluded_paths:
        - test/*
        - vendor/*
        - bin/*
        - build/*
        - src/Tests/*
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: true