language: php

env:
  global:
    - secure: GFZ4RQeYo9a57V0HUxJjIheB1q+bIRBvLt3j26TB5wusu3AEI3BAM4v/uyCAWEKO0fafW2J4L/RM5lINclH8u2C1gtzGG2nZ5NlKt7b8dM3WawZOqQaMbhgjgzR1NO3oIzSDouwvsPlTnz3pNvec73CJYsydllQJcCRNJLOEEEw=

matrix:
  include:
    - php: 5.6
    - php: 7.0

notifications:
  slack:
    secure: kireALpefhfrVR4bcpZU1WL3U584m98uO29bjkZt4720hNsgr+t0ryZZIZfF5lIBZqF9ynGO3IIfRqdqaeyof0/s5YxCLtMO7/it0eeVgo/nmUbf4aMdrkb+nGwEepBN7XNkgFF9kxfoWfIEOWhlRYOdyJLgYiVNulnhyLsE0m4=

services:
  - memcached

before_install:
  - wget -qO- https://scr.be/file/get-build-knowledge.sh | bash -E
  - bash app/config/shared_public/build/env/submodule_init-and-update.sh
  - bash app/config/shared_public/build/env/filepaths_make-and-clean.sh

install:
  - bash app/config/shared_public/build/php/runtime-conf/php_build-cfg_travis.sh
  - bash app/config/shared_public/build/php/compile-mods/php_build-mod_igbinary.sh
  - bash app/config/shared_public/build/php/compile-mods/php_build-mod_msgpack.sh
  - bash app/config/shared_public/build/php/compile-mods/php_build-mod_memcached.sh
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer install --no-interaction || travis_retry composer update --no-interaction

script:
  - bin/phpunit --verbose

after_success:
  - bash app/config/shared_public/build/env/report-success_send-coverage.sh
