language: php

env:
    global:
        secure: "eqfuY1+8J0iMntn21ug9H9DQ9cgil/kyrmGPcU7SjoQfh+MyD4tpI0XJFyvXtLeTPYt0JT9UwvQDJLLRrSqQ5k3Tz3sspleXzTiVc1f1hHhlgcKh+YN5u+kx724tCeuIO/jileArBbjyLYe6CH4weTrQgKWF49/1cisJogqmtrI="

notifications:
    slack:
        secure: "HuIz/xcPEACJvah+/h5jX4JX8Z22wgK0ZBIwn/v1KDnbl3m62EdJAfGN3jvGD+n9njmYUOCjslLHAooAC1MNntUcB9D2PJAArjD3mb9e34VtSwZ7NMfHkHZSksuaWg+nEDJrFSChvxHBp03/4JoVWjJMM2cm1TdpOMR0a/eFY1s="

branches:
    except:
        - gh-pages

php:
    - 5.6
    - 5.5
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly
        - php: 5.5

before_script:
    - travis_retry echo "no" | pecl install apcu-beta
    - phpenv config-add .travis-php.ini
    - phpenv rehash
    - mkdir -p build/logs
    - mkdir -p bin
    - travis_retry curl -s http://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
    - travis_retry php bin/composer install --no-interaction

script:
    - bin/phpunit --verbose -c phpunit.travis.xml

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
    - bin/coveralls
    - bin/test-reporter