language: php

php:
  - 5.6

services:
  - memcached

before_script:
  - sh .travis-build-igbinary.sh
  - sh .travis-build-memcached.sh
  - phpenv config-add .travis-php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = igbinary.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - mkdir -p build/logs
  - mkdir -p bin
  - travis_retry curl -s http://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
  - travis_retry php bin/composer install --no-interaction

script:
  - bin/phpunit --verbose -c phpunit.travis.xml

after_script:
  - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - bin/coveralls -vvv

notifications:
  slack:
    secure: kireALpefhfrVR4bcpZU1WL3U584m98uO29bjkZt4720hNsgr+t0ryZZIZfF5lIBZqF9ynGO3IIfRqdqaeyof0/s5YxCLtMO7/it0eeVgo/nmUbf4aMdrkb+nGwEepBN7XNkgFF9kxfoWfIEOWhlRYOdyJLgYiVNulnhyLsE0m4=
