language: php

branches:
    only:
        - master

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION="2.6.*"
        - php: 5.6
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: nightly
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: hhvm-nightly
          env: SYMFONY_VERSION="2.7.*@dev"
    allow_failures:
        - php: 5.6
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: nightly
          env: SYMFONY_VERSION="2.7.*@dev"
        - php: hhvm-nightly
          env: SYMFONY_VERSION="2.7.*@dev"
    fast_finish: true

services:
  - memcached

notifications:
  slack:
    secure: kireALpefhfrVR4bcpZU1WL3U584m98uO29bjkZt4720hNsgr+t0ryZZIZfF5lIBZqF9ynGO3IIfRqdqaeyof0/s5YxCLtMO7/it0eeVgo/nmUbf4aMdrkb+nGwEepBN7XNkgFF9kxfoWfIEOWhlRYOdyJLgYiVNulnhyLsE0m4=

before_install:
  - git submodule update --init --recursive && cd knowledge && git checkout master && cd ../
  - sh .travis-build-igbinary.sh
  - sh .travis-build-memcached.sh
  - phpenv config-add .travis-php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - mkdir -p build/logs
  - mkdir -p bin

install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - if [ "${SYMFONY_VERSION}" == "2.6.*" ]; then travis_retry composer install --no-interaction; else travis_retry composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction; fi

before_script:
  - bin/cache doctrine:database:create --no-interaction
  - bin/cache doctrine:schema:create --no-interaction
  - bin/cache doctrine:fixtures:load --no-interaction

script:
  - bin/phpunit --verbose --configuration phpunit.travis.xml

after_script:
    - bin/coveralls -c .coveralls.yml -vvv
    - if [ "${SYMFONY_VERSION}" == "2.6.*" ]; then bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi
