parameters:

    # Key Generator

    s.cache.key_generator.class:                    Scribe\CacheBundle\KeyGenerator\KeyGenerator

    # Cache Chain

    s.cache.handler_chain.class:                    Scribe\CacheBundle\Cache\Handler\Chain\HandlerChain

    # Cache Mechanisms (Types)

    s.cache.handler_type.apcu.class:                Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeApcu
    s.cache.handler_type.memcached.class:           Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeMemcached
    s.cache.handler_type.filesystem.class:          Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeFilesystem
    s.cache.handler_type.db.class:                  Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeDB

    # Entity/Repos

    s.cache.cache_db_handler_item.entity.class:     Scribe\CacheBundle\Doctrine\Entity\Cache\CacheDBHandlerItem
    s.cache.cache_db_handler_item.repo.class:       Scribe\CacheBundle\Doctrine\Repository\Cache\CacheDBHandlerItemRepository
    s.cache.cache_db_handler_prefix.entity.class:   Scribe\CacheBundle\Doctrine\Entity\Cache\CacheDBHandlerPrefix
    s.cache.cache_db_handler_prefix.repo.class:     Scribe\CacheBundle\Doctrine\Repository\Cache\CacheDBHandlerPrefixRepository

services:

    # Key Generator

    s.cache.key_generator:
        class: %s.cache.key_generator.class%
        calls:
            - [setKeyPrefix, [%s.cache.global.prefix%]]

    # Cache Chain

    s.cache.handler_chain:
        class: %s.cache.handler_chain.class%

    # Cache Mechanisms (Types)

    s.cache.handler_type.memcached:
        class: %s.cache.handler_type.memcached.class%
        lazy:  true
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.memcached.general.ttl%
            - %s.cache.handlers.memcached.general.priority%
            - %s.cache.handlers.memcached.general.disabled%
        tags:
            - { name: s.cache.handler_type }
        calls:
            - [setOptions, [%s.cache.handlers.memcached.internals%]]
            - [setServers, [%s.cache.handlers.memcached.servers%]]

    s.cache.handler_type.filesystem:
        class: %s.cache.handler_type.filesystem.class%
        lazy:  true
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.filesystem.general.ttl%
            - %s.cache.handlers.filesystem.general.priority%
            - %s.cache.handlers.filesystem.general.disabled%
        calls:
            - [proposeCacheDirectory, [%s.cache.handlers.filesystem.cache_dir%]]
        tags:
            - { name: s.cache.handler_type }

    s.cache.handler_type.db:
        class: %s.cache.handler_type.db.class%
        lazy:  true
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.db.general.ttl%
            - %s.cache.handlers.db.general.priority%
            - %s.cache.handlers.db.general.disabled%
        calls:
            - [setRepositories, [@doctrine.orm.entity_manager, @s.cache.cache_db_handler_item.repo, @s.cache.cache_db_handler_prefix.repo]]
            - [initRepositories]
        tags:
            - { name: s.cache.handler_type }

    # Repos

    s.cache.cache_db_handler_item.repo:
        class: %s.cache.cache_db_handler_item.repo.class%
        lazy:  true
        factory:
            - @doctrine
            - getRepository
        arguments:
            - %s.cache.cache_db_handler_item.entity.class%

    s.cache.cache_db_handler_prefix.repo:
        class: %s.cache.cache_db_handler_prefix.repo.class%
        factory:
            - @doctrine
            - getRepository
        arguments:
            - %s.cache.cache_db_handler_prefix.entity.class%
