---

parameters:

    # Entity/Repos

    s.cache.engine_database_item.entity.class:     Scribe\CacheBundle\Doctrine\Entity\Cache\CacheEngineDatabaseItem
    s.cache.engine_database_item.repo.class:       Scribe\CacheBundle\Doctrine\Repository\Cache\CacheEngineDatabaseItemRepository
    s.cache.engine_database_prefix.entity.class:   Scribe\CacheBundle\Doctrine\Entity\Cache\CacheEngineDatabasePrefix
    s.cache.engine_database_prefix.repo.class:     Scribe\CacheBundle\Doctrine\Repository\Cache\CacheEngineDatabasePrefixRepository

services:

    # Repos

    s.cache.engine_database_item.repo:
        class: %s.cache.engine_database_item.repo.class%
        factory:
            - @doctrine
            - getRepository
        arguments:
            - %s.cache.engine_database_item.entity.class%

    s.cache.engine_database_prefix.repo:
        class: %s.cache.engine_database_prefix.repo.class%
        factory:
            - @doctrine
            - getRepository
        arguments:
            - %s.cache.engine_database_prefix.entity.class%
