---

#
# This file is part of the Teavee Object Caching Bundle.
#
# (c) Scribe Inc.     <oss@scr.be>
# (c) Rob Frawley 2nd <rmf@scr.be>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

parameters :

    # Key Generator

    s.object_cache.key_generator.class    : Scribe\Teavee\ObjectCacheBundle\Component\Generator\KeyGenerator

    # Cache Registrar

    s.object_cache.registrar.class        : Scribe\Teavee\ObjectCacheBundle\DependencyInjection\Compiler\Registrar\CacheCompilerRegistrar

    # Cache Manager

    s.object_cache.manager.class          : Scribe\Teavee\ObjectCacheBundle\Component\Manager\CacheManager

    # Cache Methods (Memcached/Mock)

    s.object_cache.attendant_memcached.class : Scribe\Teavee\ObjectCacheBundle\Component\Cache\Memcached\MemcachedAttendant
    s.object_cache.attendant_mock.class      : Scribe\Teavee\ObjectCacheBundle\Component\Cache\Mock\MockAttendant

services :

    # Key Generator

    s.object_cache.key_generator :
        class : "%s.object_cache.key_generator.class%"
        calls :
            - [ setPrefix,    [ "%s.object_cache.generator.prefix%"    ] ]
            - [ setAlgorithm, [ "%s.object_cache.generator.algorithm%" ] ]

    # Cache Registrar

    s.object_cache.registrar :
        class : "%s.object_cache.registrar.class%"

    # Cache Manager

    s.cache :
        class     : "%s.object_cache.manager.class%"
        arguments :
            - "%s.object_cache.enabled%"
        calls :
            - [ setRegistrar, [ "@s.object_cache.registrar" ] ]

    s.object_cache :
        alias : s.cache

    s.object_cache.chain :
        alias : s.cache

    # Cache Attendants

    s.object_cache.attendant_memcached :
        class     : "%s.object_cache.attendant_memcached.class%"
        arguments :
            - "%s.object_cache.attendant.memcached.general.enabled%"
            - "%s.object_cache.attendant.memcached.general.ttl%"
        calls :
            - [ setKeyGenerator, [ "@s.object_cache.key_generator" ] ]
            - [ setOptions,      [ "%s.object_cache.attendant.memcached.options%" ] ]
            - [ setServers,      [ "%s.object_cache.attendant.memcached.servers%" ] ]
        tags  :
            - { name : s.object_cache.attendant, priority : "%s.object_cache.attendant.memcached.general.priority%" }

    s.object_cache.attendant_mock :
        class     : "%s.object_cache.attendant_mock.class%"
        arguments :
            - "%s.object_cache.attendant.mock.general.enabled%"
        calls :
            - [ setKeyGenerator, [ "@s.object_cache.key_generator" ] ]
        tags  :
            - { name : s.object_cache.attendant, priority : "%s.object_cache.attendant.mock.general.priority%" }

...
