parameters:

    scribe_cache.key_generator.class:           Scribe\CacheBundle\KeyGenerator\KeyGenerator
    scribe_cache.handler_chain.class:           Scribe\CacheBundle\Cache\Handler\Chain\HandlerChain
    scribe_cache.handler_type.apcu.class:       Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeApcu
    scribe_cache.handler_type.memcached.class:  Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeMemcached
    scribe_cache.handler_type.filesystem.class: Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeFilesystem

services:

    scribe_cache.key_generator:
        class: %scribe_cache.key_generator.class%
        calls:
            - [setKeyPrefix, [%s.cache.global.prefix%]]

    scribe_cache.handler_chain:
        class: %scribe_cache.handler_chain.class%

    scribe_cache.handler_type.memcached:
        class: %scribe_cache.handler_type.memcached.class%
        arguments:
            - @scribe_cache.key_generator
            - %s.cache.handlers.memcached.general.ttl%
            - %s.cache.handlers.memcached.general.priority%
            - %s.cache.handlers.memcached.general.disabled%
        tags:
            - { name: scribe_cache.handler_type }
        calls:
            - [setOptions, [%s.cache.handlers.memcached.internals%]]
            - [setServers, [%s.cache.handlers.memcached.servers%]]

    scribe_cache.handler_type.filesystem:
        class: %scribe_cache.handler_type.filesystem.class%
        arguments:
            - @scribe_cache.key_generator
            - %s.cache.handlers.filesystem.general.ttl%
            - %s.cache.handlers.filesystem.general.priority%
            - %s.cache.handlers.filesystem.general.disabled%
        calls:
            - [proposeCacheDirectory, [%s.cache.handlers.filesystem.cache_dir%]]
        tags:
            - { name: scribe_cache.handler_type }
