parameters:

    s.cache.keygenerator:   Scribe\CacheBundle\KeyGenerator\KeyGenerator
    s.cache.apcu.class:     Scribe\CacheBundle\CacheHandler\UserlandCacheApcu
    s.cache.memcache.class: Scribe\CacheBundle\CacheHandler\UserlandCacheMemcache
    s.cache.twig.class:     Scribe\CacheBundle\Templating\Extension\UserlandCacheExtension

services:

    s.cache.apcu:
        class:     %s.cache.apcu.class%

    s.cache.memcache:
        class:     %s.cache.memcache.class%

    s.cache.twig:
        class:     %s.cache.twig.class%
        arguments:
            - @s.cache.apcu
        tags:
            - { name: twig.extension, alias: cache.twig }
