---

parameters:

    # Key Generator

    s.cache.key_generator.class:                Scribe\CacheBundle\KeyGenerator\KeyGenerator

    # Cache Chain

    s.cache.chain.class:                        Scribe\CacheBundle\Cache\Handler\Chain\CacheChain

    # Cache Mechanisms (Types)

    s.cache.engine_memcached.class:             Scribe\CacheBundle\Cache\Handler\Engine\CacheEngineMemcached
    s.cache.engine_filesystem.class:            Scribe\CacheBundle\Cache\Handler\Engine\CacheEngineFilesystem
    s.cache.engine_database.class:              Scribe\CacheBundle\Cache\Handler\Engine\CacheEngineDatabase

services:

    # Key Generator

    s.cache.key_generator:
        class: %s.cache.key_generator.class%
        calls:
            - [setKeyPrefix, [%s.cache.global.prefix%]]

    # Cache Chain

    s.cache.chain:
        class: %s.cache.chain.class%

    s.cache.handler_chain:
        alias: s.cache.chain

    # Cache Mechanisms (Types)

    s.cache.engine_memcached:
        class: %s.cache.engine_memcached.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.engine.memcached.general.ttl%
            - %s.cache.engine.memcached.general.priority%
            - %s.cache.engine.memcached.general.disabled%
        tags:
            - { name: s.cache.engine }
        calls:
            - [setOptions, [%s.cache.engine.memcached.internals%]]
            - [setServers, [%s.cache.engine.memcached.servers%]]

    s.cache.engine_filesystem:
        class: %s.cache.engine_filesystem.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.engine.filesystem.general.ttl%
            - %s.cache.engine.filesystem.general.priority%
            - %s.cache.engine.filesystem.general.disabled%
        calls:
            - [proposeCacheDirectory, [%s.cache.engine.filesystem.cache_dir%]]
        tags:
            - { name: s.cache.engine }

    s.cache.engine_database:
        class: %s.cache.engine_database.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.engine.db.general.ttl%
            - %s.cache.engine.db.general.priority%
            - %s.cache.engine.db.general.disabled%
        calls:
            - [setManagerAndRepositories, [@doctrine.orm.entity_manager, @s.cache.engine_database_item.repo, @s.cache.engine_database_prefix.repo]]
        tags:
            - { name: s.cache.engine }
