---

parameters:

    # Key Generator

    s.cache.key_generator.class:                    Scribe\CacheBundle\KeyGenerator\KeyGenerator

    # Cache Chain

    s.cache.handler_chain.class:                    Scribe\CacheBundle\Cache\Handler\Chain\HandlerChain

    # Cache Mechanisms (Types)

    s.cache.handler_type.apcu.class:                Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeApcu
    s.cache.handler_type.memcached.class:           Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeMemcached
    s.cache.handler_type.filesystem.class:          Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeFilesystem
    s.cache.handler_type.db.class:                  Scribe\CacheBundle\Cache\Handler\Type\HandlerTypeDB

services:

    # Key Generator

    s.cache.key_generator:
        class: %s.cache.key_generator.class%
        calls:
            - [setKeyPrefix, [%s.cache.global.prefix%]]

    # Cache Chain

    s.cache.chain:
        alias: s.cache.handler_chain

    s.cache.handler_chain:
        class: %s.cache.handler_chain.class%

    # Cache Mechanisms (Types)

    s.cache.handler_type.memcached:
        class: %s.cache.handler_type.memcached.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.memcached.general.ttl%
            - %s.cache.handlers.memcached.general.priority%
            - %s.cache.handlers.memcached.general.disabled%
        tags:
            - { name: s.cache.handler_type }
        calls:
            - [setOptions, [%s.cache.handlers.memcached.internals%]]
            - [setServers, [%s.cache.handlers.memcached.servers%]]

    s.cache.handler_type.filesystem:
        class: %s.cache.handler_type.filesystem.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.filesystem.general.ttl%
            - %s.cache.handlers.filesystem.general.priority%
            - %s.cache.handlers.filesystem.general.disabled%
        calls:
            - [proposeCacheDirectory, [%s.cache.handlers.filesystem.cache_dir%]]
        tags:
            - { name: s.cache.handler_type }

    s.cache.handler_type.db:
        class: %s.cache.handler_type.db.class%
        arguments:
            - @s.cache.key_generator
            - %s.cache.handlers.db.general.ttl%
            - %s.cache.handlers.db.general.priority%
            - %s.cache.handlers.db.general.disabled%
        calls:
            - [initManagerAndRepositories, [@doctrine.orm.entity_manager, @s.cache.cache_db_handler_item.repo, @s.cache.cache_db_handler_prefix.repo]]
        tags:
            - { name: s.cache.handler_type }
