parameters:

    scribe_cache.key_generator.class:      Scribe\CacheBundle\KeyGenerator\KeyGenerator
    scribe_cache.method_chain.class:       Scribe\CacheBundle\Cache\Chain\MethodChain
    scribe_cache.handler.apcu.class:       Scribe\CacheBundle\Cache\Handlers\ApcuHandler
    scribe_cache.handler.memcached.class:  Scribe\CacheBundle\Cache\Handlers\MemcachedHandler
    scribe_cache.handler.filesystem.class: Scribe\CacheBundle\Cache\Handlers\FilesystemHandler

services:

    scribe_cache.key_generator:
        class: %scribe_cache.key_generator.class%

    scribe_cache.method_chain:
        class: %scribe_cache.method_chain.class%

    scribe_cache.handler.apcu:
        class: %scribe_cache.handler.apcu.class%
        arguments:
            - @scribe_cache.key_generator
        tags:
            - { name: scribe_cache.handler, default_priority: 1 }

    scribe_cache.handler.memcached:
        class: %scribe_cache.handler.memcached.class%
        arguments:
            - @scribe_cache.key_generator
        tags:
            - { name: scribe_cache.handler, default_priority: 2 }

    scribe_cache.handler.filesystem:
        class: %scribe_cache.handler.filesystem.class%
        arguments:
            - @scribe_cache.key_generator
        tags:
            - { name: scribe_cache.handler, default_priority: 3 }
