Scribe\CacheBundle\Entity\CacheDbHandlerItem:

    type:            entity
    table:           CacheBundle_DatabaseHandler_Item
    repositoryClass: Scribe\CacheBundle\EntityRepository\CacheDbHandlerItemRepository

    id:
        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:
        createdOn:
            type:   datetime
            column: created_on
        updatedOn:
            type:   datetime
            column: updated_on
        deletedOn:
            type:     datetime
            column:   deleted_on
            nullable: true
        cacheKey:
            type: string
            length: '600'
        cacheValue:
            type: blob

    manyToOne:
        prefix:
            targetEntity: CacheDbHandlerPrefix
            inversedBy:   items
            joinColumn:
                name:            prefixId
                referenceColumn: id

    lifecycleCallbacks: {  }
