Scribe\CacheBundle\Doctrine\Entity\Cache\CacheEngineDatabaseItem:

    type:            entity
    table:           CacheBundle_Engine_Database_Item
    repositoryClass: Scribe\CacheBundle\Doctrine\Repository\Cache\CacheEngineDatabaseItemRepository

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:

        k:
            type:   string
            length: 600

        value:
            type:     blob
            nullable: true

        ttl:
            type: integer

    manyToOne:

        prefix:
            targetEntity: CacheEngineDatabasePrefix
            inversedBy:   items
            joinColumn:
                name:            prefixId
                referenceColumn: id
